version: '3.8'

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=fakepassword
    ports:
      - 27017:27017
    volumes:
      - ./dev-db/data:/data/db